# Configurações específicas para ambiente de produção
server.address=0.0.0.0
server.port=8083
server.servlet.context-path=/feriados-nacionais

# Configurações de proxy e headers para produção
server.forward-headers-strategy=framework
server.use-forward-headers=true
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

# Configuração do Swagger para produção
springdoc.swagger-ui.server-url=https://public.api.konektadev.cv/feriados-nacionais
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.resolve-schema-properties=true
springdoc.swagger-ui.config-url=https://public.api.konektadev.cv/feriados-nacionais/v3/api-docs/swagger-config
springdoc.swagger-ui.url=https://public.api.konektadev.cv/feriados-nacionais/v3/api-docs
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=false

# Configurações de CORS para produção
spring.web.cors.allowed-origins=https://public.api.konektadev.cv
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Configurações de segurança para produção
server.ssl.enabled=false
management.server.ssl.enabled=false

# Configurações de logging para produção
logging.level.root=WARN
logging.level.feriados_nacionais.cv=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN