# Configurações específicas para ambiente Docker
server.address=0.0.0.0
server.port=8083

# Configuração do Swagger para Docker
springdoc.swagger-ui.server-url=
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.resolve-schema-properties=true

# Configurações de rede para Docker
server.forward-headers-strategy=framework
server.use-forward-headers=true

# Configuração de CORS para Docker
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*